simple_vote/urls.py
from django.contrib import admin
from django.urls import path

from main import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(
            extra_context={'menu': views.get_menu_context(), 'pagename': 'Авторизация'}
        ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('registration/', views.registration_page, name='registration'),

    path('', views.index_page, name='index'),

    path('profile/', views.profile_page, name='profile'),

    path('voting/<int:id>/complaint/', views.complaint_page, name='complaint'),

    path('voting/list/', views.voting_list_page, name='voting_list'),
    path('voting/add/', views.voting_add_page, name='voting_add'),
    path('voting/<int:id>/public/', views.voting_public_page, name='voting_public'),
    path('voting/<int:voting_id>/edit/', views.voting_edit_page, name='voting_edit'),
    path('voting/<int:voting_id>/variants/<int:variant_id>/edit/', views.variant_change, name='variant_change'),
    path('voting/<int:voting_id>/variants/<int:variant_id>/delete/', views.variant_delete, name='variant_delete'),

    path('voting/<int:voting_id>/variants/create/', views.new_variant_form_ajax, name='variant_new_form'),

    path('voting/<int:id>/delete/', views.voting_delete, name='voting_delete'),
    path('profile/<int:id>/edit/', views.profile_edit_page, name='profile_edit'),
    path('voting/<int:id>/results/', views.voting_results_page, name="voting_results"),
    # На будущее:
    # 'voting/<int:id>/' - детали голосования (доступные только автору, такие как время публикации и т.д.)
    # 'voting/<int:id>/delete/' - удаление голосования
]

main/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import get_object_or_404


class User(AbstractUser):
    status = models.CharField(max_length=255)

    def get_all_vote_facts(self):
        return VoteFact.objects.filter(author=self)

    def get_all_voted_variants(self):
        return [fact.variant for fact in self.get_all_vote_facts()]


class UserSettings(models.Model):
    user = models.OneToOneField(to=get_user_model(), on_delete=models.CASCADE)


class Voting(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    type = models.IntegerField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    published_at = models.DateTimeField(auto_now=True)

    def user_has_already_voted(self, user):
        facts = VoteFact.objects.filter(user=user)
        for fact in facts:
            for fact_variant in fact.votefactvariant_set.all():
                if fact_variant.variant.voting == self:
                    return True
        return False

    def make_votefact(self, author, variant_ids_list):
        if len(variant_ids_list) == 0:
            raise PermissionError('Список вариантов для голосования пуст')

        if self.user_has_already_voted(author):
            raise PermissionError('Пользователь уже оставлял свой голос в текущем голосовании')

        for variant_id in variant_ids_list:
            variant = get_object_or_404(VoteVariant,  id=variant_id)
            if variant.voting != self:
                raise PermissionError('Нельзя голосоваать за варианты, не привязанные к текущему голосованию')

        fact = VoteFact(user=author)
        fact.save()

        for variant_id in variant_ids_list:
            variant = get_object_or_404(VoteVariant, id=variant_id)
            record = VoteFactVariant(fact=fact, variant=variant)
            record.save()


class VoteVariant(models.Model):
    voting = models.ForeignKey(Voting, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)


class VoteFact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)


class VoteFactVariant(models.Model):
    fact = models.ForeignKey(to=VoteFact, on_delete=models.CASCADE)
    variant = models.ForeignKey(to=VoteVariant, on_delete=models.CASCADE)

main/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from main.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    agreement_checked = forms.BooleanField(
        label='Я принимаю условия соглашения',
        widget=forms.CheckboxInput()
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class CreateVotingForm(forms.Form):
    title = forms.CharField(
        label='Название голосования',
        required=True
    )
    description = forms.CharField(
        label='Описание голосования',
        required=True
    )
    type = forms.IntegerField(
        label='Тип голосования',
        min_value=1,
        max_value=3,
        required=True
    )


class EditVotingForm(forms.Form):
    title = forms.CharField(
        label='Название голосования',
        required=True
    )
    description = forms.CharField(
        label='Описание голосования',
        required=True
    )


class EditProfileForm(forms.Form):
    username = forms.CharField(
        label='Имя пользователя',
        required=True
    )
    email = forms.CharField(
        label='Email',
        required=True
    )

main/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse


from main.forms import CreateVotingForm, EditProfileForm
from main.forms import RegistrationForm, EditVotingForm
from main.models import VoteFact, VoteVariant, Voting, User, VoteFactVariant


def get_menu_context():
    return [
        {'url_name': 'index', 'name': 'Главная'},
        {'url_name': 'voting_list', 'name': 'Голосования'},
        {'url_name': 'voting_add', 'name': 'Добавить голосование'},
    ]


def get_base_context(pagename):
    return {
        'pagename': pagename,
        'menu': get_menu_context()
    }


def index_page(request):
    context = get_base_context('Главная')
    context['author'] = 'Andrew'
    context['pages'] = 4
    return render(request, 'pages/index.html', context)


@login_required
def voting_edit_page(request, voting_id):
    voting = get_object_or_404(Voting, id=voting_id)
    variants = VoteVariant.objects.filter(voting=voting)

    if not (request.user.is_staff or request.user == voting.author):
        messages.error(request, "Голосование может редактировать только его автор или модератор", extra_tags='alert-danger')

    context = {
        'menu': get_menu_context(),
        'voting': voting,
        'variants': variants,
        'pagename': 'Редактирование голосования',
        'form': EditVotingForm()
    }

    if request.method == "POST":
        form = EditVotingForm(request.POST)

        if form.is_valid():

            voting.title = form.cleaned_data['title']
            voting.description = form.cleaned_data['description']
            voting.published_at = datetime.datetime.now()
            voting.save()

            return redirect(reverse('voting_public', kwargs={'id': voting.id}))

        context['form'] = form
        context['count'] = len(variants)

    return render(request, 'pages/voting_edit.html', context)


def voting_list_page(request):
    context = get_base_context('Список голосований')
    context['votings'] = Voting.objects.all().order_by('-published_at')
    return render(request, 'pages/voting/list.html', context)


def profile_page(request):
    context = {
        'menu': get_menu_context(),
        'pagename': 'Профиль',
        'votings_count': Voting.objects.filter(author=request.user).count(),
        'votefact_count': VoteFact.objects.filter(user=request.user).count()
    }
    return render(request, 'pages/profile.html', context)


def profile_edit_page(request, id):
    user = get_object_or_404(User, id=id)
    context = {
        'menu': get_menu_context(),
        'pagename': ' Редактирование профиля',
        'votings_count': Voting.objects.filter(author=request.user).count(),
        'votefact_count': VoteFact.objects.filter(user=request.user).count()
    }

    if request.method == "POST":
        form = EditProfileForm(request.POST)

        if form.is_valid():
            user.username = form.cleaned_data['username']
            user.email = form.cleaned_data['email']
            user.save()

        return redirect('profile')
    return render(request, 'pages/profile_edit.html', context)


def voting_page(request):
    context = get_base_context('Голосование - детали')
    records_voting = []
    records_votevariants = []
    records = []
    if request.user.is_authenticated:
        records_voting = Voting.objects.filter(author=request.user).last()
        records = VoteVariant.objects.filter(voting=records_voting)

    for i in records:
        records_votevariants.append(i.description)

    context.update({
        'description': records_voting.description,
        'author': records_voting.author,
        'variants': records_votevariants,
        'type': records_voting.type,
        'publication_date': records_voting.published_at,
        'menu': get_menu_context()
    })

    return render(request, '', context)  # Внести название файла


def get_template_name_by_voting_type(voting):
    names = {
        1: 'one_of_many.html',
        2: 'some_of_many.html',
        3: 'discrete.html'
    }
    return f'pages/voting/public/{names[voting.type]}'


@login_required
def voting_public_page(request, id):
    context = get_base_context('Голосование')
    voting = get_object_or_404(Voting, id=id)
    context['voting'] = voting

    if request.method == 'POST':
        try:
            variant_ids_list = request.POST.getlist('variant', [])
            variant_ids_list = [int(variant) for variant in variant_ids_list]
            voting.make_votefact(request.user, variant_ids_list)
            messages.success(request, "Вы успешно проголосовали", extra_tags='alert-success')
            return redirect(reverse('index'))
        except ValueError:
            messages.error(request, "Что-то пошло не так...", extra_tags='alert-danger')
        except PermissionError as ex:
            context['error'] = ex
            messages.error(request, "Вы уже оставляли свой голос в текущем голосовании", extra_tags='alert-info')
    return render(request, get_template_name_by_voting_type(voting), context)


@login_required
def voting_add_page(request):
    context = get_base_context('Создание голосования')
    form = CreateVotingForm()
    context['form'] = form

    if request.method == "POST":
        form = CreateVotingForm(request.POST)

        if form.is_valid():

            count_variants = 0
            for key in request.POST.keys():
                if key.startswith('add_answer_'):
                    count_variants += 1
            factor = False if form.cleaned_data['type'] == 3 and count_variants > 2 else True

            if factor:
                voting = Voting(
                    title=form.cleaned_data['title'],
                    description=form.cleaned_data['description'],
                    type=form.cleaned_data['type'],
                    author=request.user,
                    published_at=datetime.datetime.now()
                )
                voting.save()

                for key in request.POST.keys():
                    if key.startswith('add_answer_'):
                        variant_str = request.POST[key]
                        variant_object = VoteVariant(
                            voting=voting,
                            description=variant_str
                        )
                        variant_object.save()

                return redirect(reverse('voting_public', kwargs={'id': voting.id}))
            else:
                messages.error(request, "В дискретном голосовании не может быть больше 2-х вариантов", extra_tags='alert-danger')

        context['form'] = form
    return render(request, 'pages/vote_add.html', context)


def registration_page(request):
    if request.user.is_authenticated:
        messages.error(request, "Залогиненный пользователь не может регистрироваться", extra_tags='alert-danger')

    context = {
        'pagename': 'Регистрация',
        'menu': get_menu_context()
    }
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.save()
            raw_pass = form.cleaned_data.get('password1')

            user = authenticate(username=user.username, password=raw_pass)
            login(request, user)
            return redirect(reverse('index'))
    else:
        form = RegistrationForm()
    context['form'] = form
    return render(request, 'registration/registration.html', context)


def complaint_page(request, id):
    if not request.user.is_authenticated:
        messages.error(request, "Незалогиненный пользователь не может отправлять жалобы!!!", extra_tags='alert-danger')
    voting = get_object_or_404(Voting, id=id)
    context = {
        'menu': get_menu_context(),
        'pagename': 'Добавление жалобы',
        'voting': voting,
        'user': request.user,
        'datetime': datetime.datetime.now()
    }

    return render(request, 'pages/complaint.html', context)


def variant_change(request, voting_id, variant_id):
    variant = get_object_or_404(VoteVariant, id=variant_id)
    if variant.voting.id != voting_id:
        messages.error(request, "Этот вариант не от этого голосования", extra_tags='alert-danger')
    if variant.voting.author != request.user and not request.user.is_staff:
        messages.error(request, "Только автор может редактировать варианты", extra_tags='alert-danger')

    if request.method == "POST":
        var_value = request.POST.get('add_answer')
        variant.description = var_value
        variant.save()

    return redirect(reverse('voting_edit', kwargs={'voting_id': voting_id}))


def variant_delete(request, voting_id, variant_id):
    variant = get_object_or_404(VoteVariant, id=variant_id)
    if variant.voting.id != voting_id:
        messages.error(request, "Этот вариант не от этого голосования", extra_tags='alert-danger')
    if variant.voting.author != request.user and not request.user.is_staff:
        messages.error(request, "Только автор может удалять варианты", extra_tags='alert-danger')
    variant.delete()
    return redirect(reverse('voting_edit', kwargs={'voting_id': voting_id}))

def voting_delete(request, id):
    voting = get_object_or_404(Voting, id=id)
    if voting.author.id != request.user.id and not request.user.is_staff or not request.user.is_authenticated:
        messages.error(request, "Только автор может удалять голосование", extra_tags='alert-danger')
    elif voting.author.id == request.user.id or request.user.is_staff and request.user.is_authenticated:
        voting.delete()
        messages.error(request, "Голосование удалено", extra_tags='alert-success')
    return redirect(reverse('voting_list'))


def view_vote_page(request, id):

main/templates/pages/complaint.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<div class="col-6 offset-3 mb-3">
      <div class="border rounded-2 shadow p-3 mb-5 bg-white rounded">
        <div class="row">
          <div class="col">
            <center>
              <h3> {{ voting.title }} </h3>
            </center>
          </div>
          <hr>
        </div>
        <br>
        <div class="row">
          <div class="col">
            <div class="form-text">
              {{ voting.description }}
            </div>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col">
            <h6> Автор: </h6><div class="badge bg-primary">{{ voting.author }}</div>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col">
            <h6> Опубликовано: </h6>
             {{ voting.published_at }}
          </div>
        </div>
        <br>
        <a href="{% url 'index' %}" class="btn btn-danger">Пожаловаться!!!</a>
      </div>
</div>
<br>
<br>
{% endblock %}

main/templates/pages/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col">
      <br>
      <img src="{% static 'imgs/index_four.PNG' %}" alt="People" width="400" height="350" style="float: right; margin: 0 0 5px 5px; ">
      <div style="font-size: 7rem; color: #76CDFF; font-weight: bolder; " class="text-block text-center">Voting is you super power</div>
      <div style="font-size: 2rem; color: grey; font-weight: bold;" class="text-block text-center">Use it well</div>
      <br>
      <br>
    </div>
  </div>

<br>
<div style="font-size: 2rem; color: grey; font-weight: bold;" class="text-block text-center">Если тебя ещё нет с нами, быстрее проходи регистрацию</div>
<br>
<br>

{% endblock %}

main/templates/pages/profile.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
{% if request.user.is_authenticated %}
  <br>
  <br>
  <br>
  <div class="row mt-5" align="center">

  </div>
  <div class="container">
    <div class="row">
      <div class="col position-relative">
        <img style="height:200px;"
          src="https://html5book.ru/wp-content/uploads/2016/10/profile-image.png"
          class="img-thumbnail btn position-absolute top-0 start-100 translate-middle rounded-circle float-end" alt="Аватар пользователя">
      </div>
      <div class="col position-relative">
        <p class="position-absolute top-0 start-100 translate-middle">Создано голосований:</p>
      </div>
      <br>
      <br>
      <div class="position-relative">
        <p class="fw-bold position-absolute top-0 start-100 translate-middle">{{votings_count}}</p>
      </div>
      <br>
      <br>
       <div class="col position-relative">
        <p class="position-absolute top-0 start-100 translate-middle">Оставлено голосов:</p>
      </div>
      <br>
      <br>
      <div class="position-relative">
        <p class="fw-bold position-absolute top-0 start-100 translate-middle">{{votefact_count}}</p>
      </div>
      <br>
      <br>
      <div class="col position-relative">
        <p class="position-absolute top-0 start-100 translate-middle">Ранг:</p>
      </div>
      <br>
      {% if votefact_count < 10 %}
      <div class="position-relative">
        <span class="badge bg-primary fw-bold position-absolute top-0 start-100 translate-middle">Начинающий</span>
      </div>
      {% endif %}
      {% if votefact_count >= 10 and votefact_count < 50 %}
      <div class="position-relative">
        <span class="badge bg-secondary fw-bold position-absolute top-0 start-100 translate-middle">Средний</span>
      </div>
      {% endif %}
      {% if votefact_count >= 50 %}
      <div class="position-relative">
        <span class="badge bg-warning fw-bold position-absolute top-0 start-100 translate-middle">Продвинутый</span>
      </div>
      {% endif %}
    </div>
    <br>
    <div class="row">
      <center>
        <h3>{{ user.username }}</h3>
      </center>
    </div>
    <br>
    <div class="row">
      <center>
        <p class="text-secondary">{{ user.email }}</p>
      </center>
    </div>
    <div class="row my-5">
      <center class="">
        <a href="{% url 'profile_edit' user.id %}" class="btn btn-primary">Редактировать</a>
      </center>
    </div>
  </div>
{% else %}
  <center>
    <h1 class="display-6">Войдите, чтобы посмотреть информацию!!!</h1>
    <a href="{% url 'login' %}" class="display-6">Войти</a>
  </center>
{% endif %}
<br>
<br>
{% endblock %}

main/templates/pages/profile_edit.html
% extends 'base/base.html' %}
{% block content %}
{% load static %}
{% if request.user.is_authenticated %}
  <br>
  <br>
  <br>
  <div class="row mt-5" align="center">

  </div>
  <div class="container">
    <div class="row">
      <div class="col position-relative">
        <img
          src="{% static 'imgs/user2-removebg.png' %}"
          class="img-thumbnail btn position-absolute top-0 start-100 translate-middle rounded-circle float-end" alt="Аватар пользователя">
      </div>
      <div class="col position-relative">
        <p class="position-absolute top-0 start-100 translate-middle">Создано голосований:</p>
      </div>
      <br>
      <br>
      <div class="position-relative">
        <p class="fw-bold position-absolute top-0 start-100 translate-middle">{{votings_count}}</p>
      </div>
      <br>
      <br>
       <div class="col position-relative">
        <p class="position-absolute top-0 start-100 translate-middle">Оставлено голосов:</p>
      </div>
      <br>
      <br>
      <div class="position-relative">
        <p class="fw-bold position-absolute top-0 start-100 translate-middle">{{votefact_count}}</p>
      </div>
      <br>
      <br>
      <div class="col position-relative">
        <p class="position-absolute top-0 start-100 translate-middle">Ранг:</p>
      </div>
      <br>
      {% if votefact_count < 10 %}
      <div class="position-relative">
        <span class="badge bg-primary fw-bold position-absolute top-0 start-100 translate-middle">Начинающий</span>
      </div>
      {% endif %}
      {% if votefact_count >= 10 and votefact_count < 50 %}
      <div class="position-relative">
        <span class="badge bg-secondary fw-bold position-absolute top-0 start-100 translate-middle">Средний</span>
      </div>
      {% endif %}
      {% if votefact_count >= 50 %}
      <div class="position-relative">
        <span class="badge bg-warning fw-bold position-absolute top-0 start-100 translate-middle">Продвинутый</span>
      </div>
      {% endif %}
    </div>


  <form class="col-5 mx-auto" method='post' action="/profile/{{user.id}}/edit/">
    {% csrf_token %}
  <h5 class="card-title mt-3">Имя пользователя</h5>
            <input type="text" class="form-control" name='username' required placeholder="Введите имя пользователя"
                   value="{{ user.username }}" aria-label="Введите заголовок" aria-describedby="basic-addon1">

  <h5 class="card-title mt-3">Адрес электронной почты</h5>
            <input type="text" class="form-control" style="height: 3rem;" name='email' required
                   placeholder="Введите адрес электронной почты" value="{{ user.email }}" aria-label="Введите описание"
                   aria-describedby="basic-addon1">

    <div class="row my-5">
        <input type="submit" class="btn btn-primary text-white fw-bold mt-4" value="Применить изменения">
    </div>

  </form>


{% else %}
  <center>
    <h1 class="display-6">Войдите, чтобы посмотреть информацию!!!</h1>
    <a href="{% url 'login' %}" class="display-6">Войти</a>
  </center>
{% endif %}
<br>
<br>
{% endblock %}

main/templates/pages/view_vote.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <h1>VOTING:</h1>
  <p>
    {{ voting.title }}
    {{ voting.description }}
    {{ voting.type }}
    {{ voting.author }}
    {{ voting.published_at }}
  </p>

  <h1>USER: {{ user }}</h1>


{% endblock %}

main/templates/pages/vote_add.html
{% extends 'base/base.html' %}
{% load static %}
{% block extra_css %}
     <link rel="stylesheet" href="{% static 'css/vote_add.css' %}">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
{% endblock %}
{% block content %}
        <div class="form-wrap shadow mb-5 rounded">
    <div class="profile"><img src="https://html5book.ru/wp-content/uploads/2016/10/profile-image.png">
      <h1>{{ user.username }}</h1>
    </div>
    <form method="post" action="{% url 'voting_add' %}">
      {% csrf_token %}
      <div>
        <label for="title">Вопрос</label>
        <input type="text" class="styled-text-input" name="title" id="title" required>
      </div>
      <div>
        <label for="description">Описание</label>
        <input type="text" class="styled-text-input" name="description" id="description">
      </div>
      <div class="radio">
        <span>Вид опроса</span>
        <label>
          <input type="radio" name="type" value="Анонимный">Анонимный
          <div class="radio-control anonymous"></div>
        </label>
        <label>
          <input type="radio" name="type" value="Публичный">Публичный
          <div class="radio-control public"></div>
        </label>
      </div>
      <div>
        <span id="count" style="display: none">2</span>
        <label>Варианты ответа</label>
        <div id="variants_container">
          <input type="text" class="styled-text-input" name="add_answer_0" required style="margin-top:3px;" id="add_answer_0">
          <input type="text" class="styled-text-input" name="add_answer_1" required style="margin-top:3px;" id="add_answer_1">
        </div>
        <button type="button" class="add_bottom" onclick="add_variant()">+</button>
      </div>
      <div>
        <label for="type">Тип ответа</label>
        <select name="type" id="type">
          <option>Выберите тип голосования</option>
          <option value="1">Один</option>
          <option value="2">Несколько</option>
          <option value="3">Дискретный</option>
        </select>
        <div class="select-arrow"></div>
      </div>
      <button class="bottom" type="submit">Загрузить на сайт</button>
      <br>
    </form>
  </div>
<br>
<br>

{% endblock %}
{% block extra_js %}
  <script src="{% static 'js/vote_add.js' %}"></script>
{% endblock %}

main/templates/pages/vote_results.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
{% for record in variants %}
<p>{{ record.description }}   {{ record.procent }} {{ record.count }}</p>
{% endfor %}
</body>
</html>

main/templates/pages/voting_edit.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<center>
  <div class="row">
    <div class="col">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-body">
          <form method='post'
                id="form_voting_edit"
                action="{% url 'voting_edit' voting.id %}">
            {% csrf_token %}
            <input type="hidden"
                   id="voting_identifier"
                   value="{{voting.id}}">    {# айдишник нужен для формы добавления нового варианта #}
            <h5 class="card-title">Заголовок</h5>
            <input type="text"
                   class="form-control"
                   name='title'
                   required
                   placeholder="{{ voting.title }}"
                   value="{{ voting.title }}"
                   aria-label="Введите заголовок"
                   aria-describedby="basic-addon1">
            <br>
            <h5 class="card-title">Описание</h5>
            <input type="text"
                   class="form-control"
                   style="height: 13rem;"
                   name='description'
                   required
                   placeholder="{{ voting.description }}"
                   value="{{ voting.description }}"
                   aria-label="Введите описание"
                   aria-describedby="basic-addon1">
          </form>
          <div class="row">
            <div class='col'>
              <input type="submit"
                     form="form_voting_edit"
                     class="btn btn-primary mt-4"
                     value="Применить изменения">
            </div>
          </div>

          <br>
          <h5 class="card-title">Варианты ответа</h5>

          <div class="row">
            <span id="count" style="display: none">{{count}}</span>
            {% for variant in voting.votevariant_set.all %}
              <div class="col-8">
                <form method="post" id="form_variant_{{variant.id}}" class="mt-3"  action="{% url 'variant_change' voting.id variant.id %}">
                  {% csrf_token %}
                    <input type="text" name='add_answer' id='add_answer'
                           class="form-control"
                           placeholder="Введите вариант ответа #1"
                           aria-label="Введите вариант ответа"
                           aria-describedby="basic-addon1"
                           value="{{variant.description}}"
                    >
                </form>
              </div>
              <div class="col-2 mt-3">
                <button type="submit"
                        form="form_variant_{{variant.id}}"
                        class="btn btn-warning"
                        value="Save">
                  <i class="bi bi-cloud-plus-fill"></i>
                </button>
              </div>
              <form method="post"
                    class="col-2 mt-3"
                    action="{% url 'variant_delete' voting.id variant.id %}">
                {% csrf_token %}
                <button type="submit"
                        class="btn pt-0"
                        value="Delete">
                  <i class="bi bi-trash-fill btn btn-danger" ></i>
                </button>
              </form>
            {% endfor %}
          </div>
          <div id="variants_container" class="row"></div>
          <br>
          <div class="row">
            <div class="col">
              <button type="button"
                      onclick="add_variant()"
                      class="btn btn-light border btn-sm fw-bold"
                      style="width: 10%;">+</button>
            </div>
          </div>
          <br>
        </div>
        <br>
      </div>
    </div>
  </div>
</center>
<br>
<br>
<br>
{% endblock %}
{% block extra_js %}
  <script src="{% static 'js/vote_edit.js' %}"></script>
{% endblock %}